package com.hchen.appretention;
import static com.hchen.appretention.log.AppRetentionXposedLog.logENoSave;
import androidx.annotation.NonNull;
import com.hchen.appretention.hook.EntranceMap;
import com.hchen.appretention.log.SaveLog;
import com.hchen.hooktool.HCBase;
import com.hchen.hooktool.HCEntrance;
import com.hchen.hooktool.HCInit;
import com.hchen.hooktool.utils.DeviceTool;
import com.hchen.hooktool.utils.SystemPropTool;
import java.lang.reflect.InvocationTargetException;
import java.util.Arrays;
import java.util.Objects;
import java.util.function.BiConsumer;
import de.robv.android.xposed.callbacks.XC_LoadPackage;
/**
 * Main entrance for the Xposed module.
 *
 * This class handles the initial discovery of the target process and routes the
 * hooking logic based on the device's ROM (MIUI, HyperOS, OneUI, etc.) and
 * Android SDK version. It uses a dynamic map (generated by HookProcessor)
 * to load the appropriate hook implementations for each environment.
 */
public class HookInit extends HCEntrance {
    private static final String TAG = "AppRetention";
    @NonNull
    @Override
    public HCInit.BasicData initHC(@NonNull HCInit.BasicData basicData) {
        return basicData
            .setTag(TAG)
            .setModulePackageName(BuildConfig.APPLICATION_ID)
            .setLogLevel(HCInit.LOG_D)
            .setLogExpandPath("com.hchen.appretention.hook");
    }
    @Override
    public void onLoadPackage(@NonNull XC_LoadPackage.LoadPackageParam loadPackageParam) throws Throwable {
        // Iterate through all registered hooks in the EntranceMap to find matching targets.
        EntranceMap.get().forEach(new BiConsumer<>() {
            @Override
            public void accept(String s, EntranceMap entranceMap) {
                // Filter by target package name.
                if (!entranceMap.mTargetPackage.equals(loadPackageParam.packageName))
                    return;

                // Validate ROM/Brand compatibility (e.g., Xiaomi, Samsung, or "Any").
                if (!"Any".equals(entranceMap.mTargetBrand) && !DeviceTool.isRightRom(entranceMap.mTargetBrand))
                    return;

                // Verify Android SDK version compatibility.
                if (entranceMap.mTargetSdks != null
                    && entranceMap.mTargetSdks.length > 0
                    && entranceMap.mTargetSdks[0] != 0
                    && Arrays.stream(entranceMap.mTargetSdks).noneMatch(DeviceTool::isAndroidVersion))
                    return;

                // Deep validation for Xiaomi devices, distinguishing between MIUI and HyperOS.
                if ("Xiaomi".equals(entranceMap.mTargetBrand)) {
                    if (entranceMap.mTargetOS != -1) {
                        if (entranceMap.isHyperOS) {
                            if (!DeviceTool.isHyperOSVersion(entranceMap.mTargetOS) && !entranceMap.mUpward && !entranceMap.mDownward)
                                return;
                            if (entranceMap.mUpward && !(DeviceTool.getHyperOSVersion() >= entranceMap.mTargetOS))
                                return;
                            if (entranceMap.mDownward && !(DeviceTool.getHyperOSVersion() <= entranceMap.mTargetOS))
                                return;
                        } else if (DeviceTool.getMiuiVersion() != 0f) {
                            if (!DeviceTool.isMiuiVersion(entranceMap.mTargetOS) && !entranceMap.mUpward && !entranceMap.mDownward)
                                return;
                            if (entranceMap.mUpward && !(DeviceTool.getMiuiVersion() >= entranceMap.mTargetOS))
                                return;
                            if (entranceMap.mDownward && !(DeviceTool.getMiuiVersion() <= entranceMap.mTargetOS))
                                return;
                        } else return;
                    }
                }
                // Samsung-specific routing for OneUI features.
                if (Objects.equals(entranceMap.mTargetBrand, "samsung")) {
                    if (!isEnableOneUi())
                        return;
                }

                try {
                    // Dynamically load and initialize the hook class.
                    Class<?> hookClass = getClass().getClassLoader().loadClass(s);
                    HCBase hcBase = (HCBase) hookClass.getDeclaredConstructor().newInstance();
                    String className = hcBase.TAG;
                    SaveLog.initLogToFile(className);
                    HCInit.initLoadPackageParam(loadPackageParam);
                    hcBase.onLoadPackage();
                } catch (ClassNotFoundException | NoSuchMethodException |
                         IllegalAccessException |
                         InstantiationException | InvocationTargetException e) {
                    logENoSave(TAG, e);
                }
            }
        });
    }
    private boolean isEnableOneUi() {
        return SystemPropTool.getProp("persist.hchen.oneui.enable", false);
    }
}
